language: python
python:
- 2.7
services:
- docker
before_install:
- sudo apt-get update
- docker-compose --version
- pip install docker-compose
- docker-compose --version
install:
- cd 7.11.2
- docker-compose build
- docker-compose up -d
- docker-compose ps
before_script:
- pip install requests
- pip install docker
- cd $TRAVIS_BUILD_DIR
script:
- bash ./.travis/linters.sh
- python tests.py
notifications:
  slack:
    rooms:
    - optimum-team:GycletOWK4Kt95GktwYwfUMp#build
env:
  matrix:
  - DOCKER_CONTENT_TRUST=0
  global:
  - secure: DkBXI4WTX+tkCXsfnJwySq+vvmRcyjakt8zrrErggz3uYEXAV7k/0dwn0LobP+AMODbxESjqB1KH48qRzFrs569od6E7MZNZS3omdOjKgrx8UYCanQK8PzxfAGFp1ZTT9Ruqu8gnuw0MCQRNd5A3wiy19CjhtXJISEv0RXZxManh4LOJntGCoJcHsHv/nrD0JH0eJ8qk27NYe7bxTR0sNXu5NoLw4RIq8hU4v70a82OtpCEzu64WkVG1AdI7NkOX0cR6G26sY/KrjGb+fXy8AmSreuvA0cnIGiQlibqH/23LFZ6pff1j7GOEzMor42NfRsQW6IEnxF0OZUxcAKTJxn98qAAQfRURAX2WLnuGaEnitL0JYTN3OIOpGTFPdMartziczPHjcyAO8/+Hlux6lqpnDGZSkuNgaEA+z6sT1Xrsj8W1Z+fkbb9w1UQ0/jpgd2sDbatZBXrNRZpk7N0bQF2frT8QUDMHWgTow31Xo8RYPpGMUfMcKnJdY/XgHVP0yDZfpuKMmUKH7L7RWa99ie2X8m9N0sdAufBoX+V+rsBZWI/SOY2p9viza+dlW6cBL5HOq/a9Wp5TxZM7AHzR97EA1RkXkmt50BLxkMGwdB0ZfYlfxh+PMHmu9QMNH5G8a4oev1C3neAkOxj08koO04H6/FKJeiwlC5U7kyFfbx0=
  - secure: B97tomFBdIIAIyZs7r981Tb2ODzA3/omnfrWZI5lQq0uURDSISJM93chOHKFNgZ11aRj0rHK1i8ZeDw7jliF9rP0Lzhx6imwAQHn4o8zxgsDtpadXxcCxJxBNoNUl7tUbhzTpW3HZjzgPeHabvyNukZxlak5OfZ6D/Pb+JI/ED2AH0JtxpqTEK482OoZmmya35i1mRqnyyXI82vzmDUYyaadkt1awvrvX21l40Mk/iakHY3o8z1CAjjcauDqlk2jP5moFZeUFy2qlKiKQoOKzzXadV9PbopKCJKEbEdGWvlsx/6y0nfRaPT1Q5pbaS+X2rKwsuUqtXzx1wRITkKSTutQ2HNIw34CjeCDcWos7No47T0+KFeHTLCwQLX4ZR6vJN08E5y7IaYIefOPGW7hYqNM6wI2D53kog+LKidNV2t83F46ZnF8xR7O4ol3bfkHzK2goVHhjXgN8eEYautgE9FOUUmAvRYDu4jhxBRTIi/UipThaByYXKeGFVfpzRRUJGeh02aypml1UeN9LcYwTrwZwGROwSMpcH0hXRfEw5JUGMdWSFbvCd4yppH0T48YXi7hxCNfxToTsNsrfn5ErREfGBAKv/S1Lz2Sc8PpEJOlXezjE7IVVNvk5AQqMf1m8b6o2R8yugztF1PBScfrf/74ulIgMpBEU2v8nOZmSQg=
